### ISSUE TITLE
quotes within quotes

### ISSUE THREAD

**Issue by tallpeak** [reZach/listtosql#1]
Could you add a line like this:
					text = text.replace(/\x27/g, "\x27\x27"); // ' to '' 
before:
					text = text.replace(/^(.+)$/gm, "'$1', ");

**Comment by reZach** [comment]
Thanks for this contribution @tallpeak. Can you give me an example of why we would want to add this line? An example case would be helpful to see.

**Comment by reZach** [comment]
Sorry for taking so long to get to this @tallpeak , with commit https://github.com/reZach/listtosql/commit/dc9cab2158f8339ca34c92a4a0f304763df412fc the extension has now been updated with your suggestion.
